### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by iamskok** [jhardy/sache#53]
Can't upload package because of Internal Server Error. 

http://monosnap.com/image/CQ0s7DiIsOipzVkDqRyNm7s9QhcA73

**Comment by jhardy** [comment]
Thanks for the heads up, can you give it another shot and see if it works?

**Comment by iamskok** [comment]
It's still not working (Internal Server Error) :cry:

**Comment by jhardy** [comment]
Ok, try once more if you wouldn't mind.

**Comment by iamskok** [comment]
Works, thank you :+1:
